---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keys-app-front-cm
  labels:
    app: keys-app-front
    tier: frontend

data:
  extras.conf: |+
    ## Descomentar para activar user y pass, asegurarse
    #auth_basic "registry mobydigital";
    #auth_basic_user_file /etc/nginx/registry.password;
    add_header X-Robots-Tag "noindex, nofollow, noarchive, nosnippet";
    add_header X-XSS-Protection "1; mode=block";

  default.conf: |+
    server {
      listen 80;
      server_name _;

      include /etc/nginx/extras.conf;

      keepalive_requests        1000;
      keepalive_timeout   75 75;

      sendfile on;
      sendfile_max_chunk 1m;

      default_type application/octet-stream;

      gzip               on;
      #gzip_http_version 1.1;
      gzip_disable       "MSIE [1-6]\.(?!.*SV1)";
      gzip_min_length    1256;
      gzip_proxied       expired no-cache no-store private auth;
      gzip_vary          on;
      gzip_types         text/plain
                         text/css
                         image/png
                         image/gif
                         image/jpeg
                         application/x-javascript
                         text/xml
                         application/xml
                         application/xml+rss
                         text/javascript
                         image/svg+xml;
      gzip_comp_level    6;

      root /usr/share/nginx/html;

      location ~* \.(?:jpe?g|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
        expires max;
        access_log off;
        add_header Cache-Control "public";
      }

      location / {
        try_files $uri $uri/ /index.html =404;
      }

    }
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    dev.okteto.com/auto-ingress: "true"
  name: keys-app-front
  labels:
    project: keys-app-front

spec:  
  selector:
    project: keys-app-front
    
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keys-app-front  
spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: keys-app-front
    spec:
      containers:
        - name: keys-app-front
          image: mobydigital/keys-app-front:IMAGETAG
          imagePullPolicy: Always
          volumeMounts:
          #  - name: keys-app-front-tls-vol
          #    mountPath: /etc/nginx/cert
          #    readOnly: true
            - name: keys-app-front-conf-vol
              subPath: extras.conf
              mountPath: /etc/nginx/extras.conf
            - name: keys-app-front-conf-vol
              subPath: default.conf
              mountPath: /etc/nginx/conf.d/default.conf
          ports:
            - containerPort: 80
      volumes:
        # - name: keys-app-front-tls-vol
        #   secret:
        #     secretName: keys-app-front-secret
        - name: keys-app-front-conf-vol
          configMap:
            name: keys-app-front-cm
            items:
              - key: extras.conf
                path: extras.conf
              - key: default.conf
                path: default.conf
